version: '3.9'
services:
  postgres:
    image: postgres:13.5    
    restart: always
    environment:            
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=twitter
    ports:
      - '5432:5432'   