openapi: 3.0.0
info:
  version: 1.0.0
  title: twitter-backend-clone
  description: Backend clone of Twitter in Node.js, TypeScript
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
paths:
  /api/v1/user/{username}:
    parameters:
      - in: path
        name: username
        schema:
          type: string
        required: true
        description: Username of the user

    get:
      summary: Get user by username
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Delete user by username
      responses:
        '204':
          description: User deleted successfully
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Update user by username
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdatePayload'
      responses:
        '204':
          description: User updated successfully
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/tweet/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
        description: ID of the tweet

    get:
      summary: Get tweet by ID
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tweet'
        '404':
          description: Tweet not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Delete tweet by ID
      responses:
        '204':
          description: Tweet deleted successfully
        '404':
          description: Tweet not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/tweet:
    post:
      summary: Create a new tweet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTweet'
      responses:
        '201':
          description: Tweet created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tweet'
        '400':
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

# Components section
components: {}
# Add more schemas as needed
servers:
  - url: 'http://localhost:3000/api/v1/docs'
    description: Local server

